python main_train.py \
--image_dir /maoxx/ljb/data/iu_xray/images/ \
--ann_path /maoxx/ljb/data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 32 \
--epochs 25 \
--save_dir results/iu_xray \
--step_size 50 \
--gamma 0.1 \
--seed 9223
